export enum BetType {
    SPLIT = "split",
    INSURE = "insure",
    SPIN = "spin",
    COLLECT = "collect",
    DRAW = "draw",
    PICKSYMBOL = "picksymbol",
    BONUS = "bonus",
    DROP = "drop",
    SHIFTREELS = "shiftreels",
    PICKWINTYPE = "pickwintype",
    DEAL = "deal",
    BONUSACTION = "bonusaction",
    RESPIN = "respin",
    DOUBLE = "double",
    FREESPIN = "freespin",
    STAND = "stand",
    PLATINUMACTION = "platinumaction",
    INIT = "init",
    HIT = "hit",
    STANDART = "standart",
    FREE = "free",
    TUMBLE = "tumble",
    HALFCOLLECT = "halfcollect",
    SG = "SG"
}